import React from 'react';
import {
  AlertCircle,
  AlertTriangle,
  ArrowLeft,
  ArrowRight,
  ArrowUpRight,
  Award,
  BarChart2,
  BarChart3,
  Bell,
  BookOpen,
  Box,
  Briefcase,
  Building2,
  Check,
  CheckCheck,
  CheckCircle,
  CheckCircle2,
  ChevronDown,
  ChevronRight,
  Circle,
  Clock,
  Cloud,
  Code,
  Code2,
  Compass,
  Cpu,
  CreditCard,
  Database,
  DollarSign,
  Download,
  FileQuestion,
  FileUp,
  Gauge,
  GraduationCap,
  HelpCircle,
  Landmark,
  Layers,
  Layout,
  LayoutDashboard,
  Lightbulb,
  Loader2,
  Lock,
  LogIn,
  LogOut,
  MapPin,
  Network,
  Play,
  Plus,
  RefreshCw,
  RotateCcw,
  Search,
  Server,
  Shield,
  ShieldCheck,
  Smartphone,
  Sparkles,
  Star,
  Target,
  TrendingUp,
  User,
  Users,
  Wand2,
  X,
  XCircle,
  Zap,
  ZoomIn
} from 'lucide-react';

const iconMap = {
  'alert-circle': AlertCircle,
  'alert-triangle': AlertTriangle,
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  'arrow-up-right': ArrowUpRight,
  'award': Award,
  'bar-chart-2': BarChart2,
  'bar-chart-3': BarChart3,
  'bell': Bell,
  'book-open': BookOpen,
  'box': Box,
  'briefcase': Briefcase,
  'building-2': Building2,
  'check': Check,
  'check-check': CheckCheck,
  'check-circle': CheckCircle,
  'check-circle-2': CheckCircle2,
  'chevron-down': ChevronDown,
  'chevron-right': ChevronRight,
  'circle': Circle,
  'clock': Clock,
  'cloud': Cloud,
  'code': Code,
  'code-2': Code2,
  'compass': Compass,
  'cpu': Cpu,
  'credit-card': CreditCard,
  'database': Database,
  'dollar-sign': DollarSign,
  'download': Download,
  'file-question': FileQuestion,
  'file-up': FileUp,
  'gauge': Gauge,
  'graduation-cap': GraduationCap,
  'help-circle': HelpCircle,
  'landmark': Landmark,
  'layers': Layers,
  'layout': Layout,
  'layout-dashboard': LayoutDashboard,
  'lightbulb': Lightbulb,
  'loader-2': Loader2,
  'lock': Lock,
  'log-in': LogIn,
  'log-out': LogOut,
  'map-pin': MapPin,
  'network': Network,
  'play': Play,
  'plus': Plus,
  'refresh-cw': RefreshCw,
  'rotate-ccw': RotateCcw,
  'search': Search,
  'server': Server,
  'shield': Shield,
  'shield-check': ShieldCheck,
  'smartphone': Smartphone,
  'sparkles': Sparkles,
  'star': Star,
  'target': Target,
  'trending-up': TrendingUp,
  'user': User,
  'users': Users,
  'wand-2': Wand2,
  'x': X,
  'x-circle': XCircle,
  'zap': Zap,
  'zoom-in': ZoomIn
};

export default function Icon({ name, size = 18, className = "" }) {
  const LucideIcon = iconMap[name];
  
  if (!LucideIcon) {
    return <span className={`inline-block ${className}`} style={{ width: size, height: size }} />;
  }
  
  return <LucideIcon size={size} className={className} />;
}
