import React from 'react';

export default function RoadmapPDFTemplate({
  user,
  targetRole,
  readinessScore,
  verifiedKnown,
  domainClusters,
  careerPhases
}) {
  return (
    <div id="pdf-export-template" className="absolute left-[-9999px] top-0 w-[800px] bg-white text-slate-900 p-10 font-sans" style={{ minHeight: '1122px' }}>
      
      {/* HEADER */}
      <div className="border-b-4 border-brand-900 pb-6 mb-8 flex justify-between items-end">
        <div>
          <h1 className="text-3xl font-black text-brand-900 mb-2">Career Skilling Roadmap</h1>
          <p className="text-lg text-slate-600 font-medium">Prepared for: <span className="font-bold text-slate-900">{user?.name || 'MoSPI Official'}</span></p>
          <p className="text-sm text-slate-500">{user?.email}</p>
        </div>
        <div className="text-right">
          <p className="text-sm font-bold text-slate-500 uppercase tracking-widest mb-1">Target Role</p>
          <p className="text-xl font-black text-slate-900">{targetRole || 'MoSPI Cadre'}</p>
          <div className="mt-2 inline-block bg-blue-50 border border-blue-200 text-blue-800 px-3 py-1 rounded-full text-sm font-bold">
            Readiness Score: {Math.round(readinessScore || 0)}%
          </div>
        </div>
      </div>

      {/* SECTION: STRENGTHS */}
      {verifiedKnown?.length > 0 && (
        <div className="mb-8">
          <h2 className="text-xl font-bold text-slate-800 border-b border-slate-200 pb-2 mb-4">Validated Strengths</h2>
          <div className="flex flex-wrap gap-2">
            {verifiedKnown.map((skill, idx) => (
              <span key={idx} className="bg-emerald-50 border border-emerald-200 text-emerald-800 px-3 py-1 rounded-lg text-xs font-bold">
                ✓ {skill}
              </span>
            ))}
          </div>
        </div>
      )}

      {/* SECTION: SKILLS TO ACQUIRE */}
      <div className="mb-10">
        <h2 className="text-xl font-bold text-slate-800 border-b border-slate-200 pb-2 mb-4">Competency Gaps by Domain</h2>
        <div className="grid grid-cols-2 gap-6">
          {domainClusters?.map((cluster, idx) => (
            <div key={idx} className="bg-slate-50 border border-slate-200 rounded-xl p-4">
              <h3 className="font-bold text-slate-800 mb-3">{cluster.title}</h3>
              <div className="flex flex-col gap-2">
                {cluster.skills.map((skill, sIdx) => (
                  <div key={sIdx} className="text-sm text-slate-600 flex items-center gap-2">
                    <span className="w-1.5 h-1.5 rounded-full bg-blue-500"></span>
                    {skill}
                  </div>
                ))}
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* SECTION: ROADMAP PHASES */}
      <div className="mb-8">
        <h2 className="text-xl font-bold text-slate-800 border-b border-slate-200 pb-2 mb-6">Execution Roadmap</h2>
        <div className="space-y-6">
          {careerPhases?.map((phase, idx) => (
            <div key={idx} className="flex gap-4">
              <div className="w-12 h-12 flex-shrink-0 bg-blue-100 border border-blue-300 text-blue-800 rounded-full flex items-center justify-center font-black text-xl">
                {phase.stepNumber}
              </div>
              <div className="flex-1 pt-2">
                <h3 className="text-lg font-black text-slate-900 mb-1">{phase.title}</h3>
                <p className="text-sm text-slate-600 mb-3">{phase.focus}</p>
                <div className="flex flex-wrap gap-2">
                  {phase.skills?.map((skill, sIdx) => (
                    <span key={sIdx} className="bg-white border border-slate-300 text-slate-700 px-2 py-1 rounded text-xs font-semibold">
                      {skill}
                    </span>
                  ))}
                </div>
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* FOOTER */}
      <div className="mt-auto pt-8 border-t border-slate-200 text-center text-xs text-slate-400">
        Generated by MoSPI National Skilling Command Center &bull; iGOT Karmayogi Integration
      </div>
      
    </div>
  );
}
